### ISSUE TITLE
nodejs support

### ISSUE THREAD

**Issue by EtianChamayMA** [yahoo/kubectl-flame#53]
Hi, from the description it seems nodejs is not supported.

did I understand it correctly?

thanks in advance

**Comment by r4j4h** [comment]
I am not associated with this project, but I believe you understand correctly.

For moving towards adding support, I believe an example approach that roughly follows the [spirit of how other languages are implemented in kubectl-flame](https://github.com/VerizonMedia/kubectl-flame#how-it-works) is documented in the official node.js docs: https://nodejs.org/en/docs/guides/diagnostics-flamegraph/#create-a-flame-graph-with-system-perf-tools

**Comment by bsergean** [comment]
If under the hood perf top or similar is called, I believe the approach would work for C++ binaries as well. (it would help with this other issue-> https://github.com/yahoo/kubectl-flame/issues/55).
