### ISSUE TITLE
Java default event should be CPU not WALL

### ISSUE THREAD

**Issue by loicmathieu** [yahoo/kubectl-flame#63]
As this is the default one from async-profiler.
And it's also more useful on Java as wall clock profiling via async-profiler is a special mode and should also use the per-thread mode that is not activated: https://github.com/jvm-profiling-tools/async-profiler#wall-clock-profiling

I can provide a PR for it if you help me to start contributing ;)

**Comment by edeNFed** [comment]
Sounds good to me, I'll be happy to approve such PR 😄
